apiVersion: v1
kind: Secret
metadata:
  name: algofox-secrets
  namespace: algofox
type: Opaque
stringData:
  # App Secrets
  BETTER_AUTH_SECRET: "zpN6vAuvJwJ79IkeWIOPlwUoA5M1F2HG"
  BETTER_AUTH_URL: "http://localhost:3000" # NOTE: Update this to your production domain for deployment

  # Auth Clients
  GOOGLE_CLIENT_ID: "346668050279-5v30ltt30k72u6husfgeq1d3gigq6dhq.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  GITHUB_CLIENT_ID: "Ov23lixEijoEvfYkBCVs"
  GITHUB_CLIENT_SECRET: "3564b87377a2561fbb74d47afdedb94f87a9e5fb"
  MICROSOFT_CLIENT_ID: "f6010c02-6a43-4879-9b41-f08ca160241e"
  MICROSOFT_CLIENT_SECRET: "YGv8Q~VtCKO~ZnLkGH5v2gf1UEonHwC0FpYT6be1"

  # Judge0 Configuration
  JUDGE0_URL: "http://165.232.176.157:2358"

  # S3/CDN Configuration
  S3_ACCESS_KEY_ID: "AKIAZO6B4EXYRU2KDURB"
  S3_SECRET_ACCESS_KEY: "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"
  S3_REGION: "ap-south-2"
  S3_BUCKET_NAME: "algofox"
  S3_PUBLIC_DOMAIN: "d1537vh1uabczq.cloudfront.net"

  # Other Services
  TELEGRAM_BOT_TOKEN: "8360224792:AAEqYIb4GVmaLwSvN5tFSw9WNLBEte-nMTA"

  # Database & Redis (Internal K8s DNS)
  POSTGRES_PASSWORD: "algofox"
  REDIS_PASSWORD: ""
  DATABASE_URL: "postgresql://algofox:algofox@postgres:5432/algofox"
  REDIS_URL: "redis://redis:6379"
