apiVersion: v1
kind: Secret
metadata:
  name: algofox-secrets
  namespace: algofox
type: Opaque
stringData:
  # App Secrets
  BETTER_AUTH_SECRET: "REPLACEME_BEFORE_DEPLOY"
  BETTER_AUTH_URL: "http://example.com"

  # Auth Clients
  GOOGLE_CLIENT_ID: "REPLACEME"
  GOOGLE_CLIENT_SECRET: "REPLACEME"
  GITHUB_CLIENT_ID: "REPLACEME"
  GITHUB_CLIENT_SECRET: "REPLACEME"
  MICROSOFT_CLIENT_ID: "REPLACEME"
  MICROSOFT_CLIENT_SECRET: "REPLACEME"

  # Judge0 Configuration
  JUDGE0_URL: "http://judge0:2358"

  # S3/CDN Configuration
  S3_ACCESS_KEY_ID: "REPLACEME"
  S3_SECRET_ACCESS_KEY: "REPLACEME"
  S3_REGION: "ap-south-2"
  S3_BUCKET_NAME: "algofox"
  S3_PUBLIC_DOMAIN: "REPLACEME"

  # Other Services
  TELEGRAM_BOT_TOKEN: "REPLACEME"

  # External Database & Redis
  DATABASE_URL: "postgres://USER:PASSWORD@HOST:PORT/defaultdb?sslmode=require"
  REDIS_URL: "rediss://USER:PASSWORD@HOST:PORT"
